prep work

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -31,115 +31,115 @@ env:
     rm bin/nightly/resources/.geode_cache
 
 jobs:
-  build-windows:
-    name: Build Windows
-    runs-on: ubuntu-24.04
+  #build-windows:
+  #  name: Build Windows
+  #  runs-on: ubuntu-24.04
 
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v4
-      with:
-        submodules: recursive
+  #  steps:
+  #  - name: Checkout
+  #    uses: actions/checkout@v4
+  #    with:
+  #      submodules: recursive
 
-    - name: Prepare for Build Debug Info
-      id: build-debug-info
-      uses: ./.github/actions/build-debug-info
-      with:
-        has-sccache: ${{ inputs.use-ccache }}
-      if: inputs.build-debug-info
+  #  - name: Prepare for Build Debug Info
+  #    id: build-debug-info
+  #    uses: ./.github/actions/build-debug-info
+  #    with:
+  #      has-sccache: ${{ inputs.use-ccache }}
+  #    if: inputs.build-debug-info
 
-    - name: Setup caches
-      uses: ./.github/actions/setup-cache
-      with:
-        host: linux
-        target: win
-        use-ccache: ${{ github.event_name != 'workflow_dispatch' || inputs.use-ccache }}
+  #  - name: Setup caches
+  #    uses: ./.github/actions/setup-cache
+  #    with:
+  #      host: linux
+  #      target: win
+  #      use-ccache: ${{ github.event_name != 'workflow_dispatch' || inputs.use-ccache }}
 
-    - name: Setup Ninja
-      uses: ./.github/actions/setup-ninja
-      with:
-        host: linux
+  #  - name: Setup Ninja
+  #    uses: ./.github/actions/setup-ninja
+  #    with:
+  #      host: linux
 
-    - name: Setup CLI
-      uses: geode-sdk/cli/.github/actions/setup@main
+  #  - name: Setup CLI
+  #    uses: geode-sdk/cli/.github/actions/setup@main
 
-    - name: Download xwin
-      uses: robinraju/release-downloader@v1.10
-      with:
-        repository: Jake-Shadle/xwin
-        latest: true
-        fileName: 'xwin-*-x86_64-unknown-linux-musl.tar.gz'
-        tarBall: false
-        zipBall: false
-        out-file-path: "epic-xwin"
+  #  - name: Download xwin
+  #    uses: robinraju/release-downloader@v1.10
+  #    with:
+  #      repository: Jake-Shadle/xwin
+  #      latest: true
+  #      fileName: 'xwin-*-x86_64-unknown-linux-musl.tar.gz'
+  #      tarBall: false
+  #      zipBall: false
+  #      out-file-path: "epic-xwin"
 
-    - name: Prepare xwin
-      run: |
-        tar -xzf epic-xwin/xwin-*-x86_64-unknown-linux-musl.tar.gz -C epic-xwin
-        mv epic-xwin/xwin-*-x86_64-unknown-linux-musl/xwin ./xwin
-        ./xwin --arch x86 --sdk-version 10.0.22621 --accept-license list
+  #  - name: Prepare xwin
+  #    run: |
+  #      tar -xzf epic-xwin/xwin-*-x86_64-unknown-linux-musl.tar.gz -C epic-xwin
+  #      mv epic-xwin/xwin-*-x86_64-unknown-linux-musl/xwin ./xwin
+  #      ./xwin --arch x86 --sdk-version 10.0.22621 --accept-license list
 
-    # this caches '.xwin-cache/**/*' but that's actually only gonna
-    # contain the manifest cuz we only ran `xwin list` so far
-    - name: Setup xwin Cache
-      id: xwin-cache
-      uses: actions/cache@v4
-      with:
-        path: .xwin-cache
-        key: xwin-win-v1-${{ hashFiles('.xwin-cache/**/*') }}
+  #  # this caches '.xwin-cache/**/*' but that's actually only gonna
+  #  # contain the manifest cuz we only ran `xwin list` so far
+  #  - name: Setup xwin Cache
+  #    id: xwin-cache
+  #    uses: actions/cache@v4
+  #    with:
+  #      path: .xwin-cache
+  #      key: xwin-win-v1-${{ hashFiles('.xwin-cache/**/*') }}
 
-    - name: Download Windows headers
-      run: ./xwin --arch x86 --sdk-version 10.0.22621 --accept-license splat --include-debug-libs
-      if: steps.xwin-cache.outputs.cache-hit != 'true'
+  #  - name: Download Windows headers
+  #    run: ./xwin --arch x86 --sdk-version 10.0.22621 --accept-license splat --include-debug-libs
+  #    if: steps.xwin-cache.outputs.cache-hit != 'true'
 
-    - name: Download clang-msvc-sdk toolchain
-      uses: actions/checkout@v4
-      with:
-        repository: 'geode-sdk/clang-msvc-sdk'
-        path: toolchain
-        submodules: recursive
+  #  - name: Download clang-msvc-sdk toolchain
+  #    uses: actions/checkout@v4
+  #    with:
+  #      repository: 'geode-sdk/clang-msvc-sdk'
+  #      path: toolchain
+  #      submodules: recursive
 
-    - name: Install Clang 19
-      run: |
-        sudo rm -f /var/lib/man-db/auto-update
-        sudo apt install -y clang-19 clang-tools-19 lld-19
+  #  - name: Install Clang 19
+  #    run: |
+  #      sudo rm -f /var/lib/man-db/auto-update
+  #      sudo apt install -y clang-19 clang-tools-19 lld-19
 
-    - name: Configure
-      run: ${{ env.base-configure-command }} -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN ${{ steps.build-debug-info.outputs.extra-configure }}
-      env:
-        SPLAT_DIR: ${{ github.workspace }}/.xwin-cache/splat
-        TOOLCHAIN: ${{ github.workspace }}/toolchain/clang-cl-msvc.cmake
-        HOST_ARCH: x86
-        CLANG_VER: 19
-        LLVM_VER: 19
+  #  - name: Configure
+  #    run: ${{ env.base-configure-command }} -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN ${{ steps.build-debug-info.outputs.extra-configure }}
+  #    env:
+  #      SPLAT_DIR: ${{ github.workspace }}/.xwin-cache/splat
+  #      TOOLCHAIN: ${{ github.workspace }}/toolchain/clang-cl-msvc.cmake
+  #      HOST_ARCH: x86
+  #      CLANG_VER: 19
+  #      LLVM_VER: 19
 
-    - name: Build
-      run: |
-        ${{ env.base-build-command }}
-        ${{ steps.build-debug-info.outputs.extra-build }}
+  #  - name: Build
+  #    run: |
+  #      ${{ env.base-build-command }}
+  #      ${{ steps.build-debug-info.outputs.extra-build }}
 
-    - name: Upload Artifacts
-      uses: actions/upload-artifact@v4
-      with:
-        name: geode-win
-        path: ./bin/nightly
+  #  - name: Upload Artifacts
+  #    uses: actions/upload-artifact@v4
+  #    with:
+  #      name: geode-win
+  #      path: ./bin/nightly
 
-    - name: Package Installer
-      run: |
-        sudo apt install nsis
-        makensis -WX -V3 ./installer/windows/installer.nsi
+  #  - name: Package Installer
+  #    run: |
+  #      sudo apt install nsis
+  #      makensis -WX -V3 ./installer/windows/installer.nsi
 
-    - name: Upload Installer
-      uses: actions/upload-artifact@v4
-      with:
-        name: geode-installer-win
-        path: './installer/windows/geode-installer-win.exe'
+  #  - name: Upload Installer
+  #    uses: actions/upload-artifact@v4
+  #    with:
+  #      name: geode-installer-win
+  #      path: './installer/windows/geode-installer-win.exe'
 
-    - name: Complete Build Debug Info
-      uses: ./.github/actions/build-debug-info-post
-      with:
-        target: win
-      if: inputs.build-debug-info && (success() || failure())
+  #  - name: Complete Build Debug Info
+  #    uses: ./.github/actions/build-debug-info-post
+  #    with:
+  #      target: win
+  #    if: inputs.build-debug-info && (success() || failure())
 
   # build-mac:
   #   name: Build macOS
@@ -295,7 +295,7 @@ jobs:
   publish:
     name: Publish
     runs-on: ubuntu-latest
-    needs: [ build-windows, build-android ]
+    needs: [ build-android ]
     if: github.ref == 'refs/heads/gdps'
     steps:
       - name: Checkout
@@ -310,10 +310,10 @@ jobs:
       - name: Download Artifacts
         uses: actions/download-artifact@v4
 
-      - name: Move Installers
-        run: |
-          mv geode-installer-win/geode-installer-win.exe geode-installer-${{ steps.ref.outputs.hash }}-win.exe
-          mv ./installer/linux/install.sh geode-installer-${{ steps.ref.outputs.hash }}-linux.sh
+      #- name: Move Installers
+      #  run: |
+      #    mv geode-installer-win/geode-installer-win.exe geode-installer-${{ steps.ref.outputs.hash }}-win.exe
+      #    mv ./installer/linux/install.sh geode-installer-${{ steps.ref.outputs.hash }}-linux.sh
 
       #   mv geode-installer-mac/geode-installer-mac.pkg geode-installer-${{ steps.ref.outputs.hash }}-mac.pkg
 
@@ -324,11 +324,11 @@ jobs:
       #    files: geode-mac/Geode.dylib geode-mac/GeodeBootstrapper.dylib
       #    dest: geode-${{ steps.ref.outputs.hash }}-mac.zip
 
-      - name: Zip Windows Artifacts
-        uses: vimtor/action-zip@v1.2
-        with:
-          files: geode-win/XInput9_1_0.dll geode-win/Geode.dll geode-win/GeodeUpdater.exe geode-win/Geode.lib geode-win/Geode.pdb
-          dest: geode-${{ steps.ref.outputs.hash }}-win.zip
+      #- name: Zip Windows Artifacts
+      #  uses: vimtor/action-zip@v1.2
+      #  with:
+      #    files: geode-win/XInput9_1_0.dll geode-win/Geode.dll geode-win/GeodeUpdater.exe geode-win/Geode.lib geode-win/Geode.pdb
+      #    dest: geode-${{ steps.ref.outputs.hash }}-win.zip
 
       - name: Zip Android32 Artifacts
         uses: vimtor/action-zip@v1.2
@@ -352,8 +352,5 @@ jobs:
           body: |
             Geode development release for commit ${{ github.sha }}. Since this is not a regular release, Geode will not install the resources automatically, so you should use the installer if you want them.
           files: |
-            ./geode-installer-${{ steps.ref.outputs.hash }}-win.exe
-            ./geode-installer-${{ steps.ref.outputs.hash }}-linux.sh
-            ./geode-${{ steps.ref.outputs.hash }}-win.zip
             ./geode-${{ steps.ref.outputs.hash }}-android32.zip
             ./resources.zip
